name: default

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  main:
    name: Build and test image

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      # Fetch host compiler
      - uses: dlang-community/setup-dlang@v1
        name: Install host LDC
        with:
          compiler: ldc-latest

      - name: Run make
        run: make all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub
      #   if: ${{ github.event_name == 'push' }}
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: false
          tags: dlangtour/core-dreg:latest
          context: .

      - name: Run test.sh
        run: ./test.sh "dlangtour/core-dreg:latest"

    runs-on: ubuntu-latest
